version: "3.9"
services:
  api:
    image: "customer-svc"
    ports: 
      - "8082:8080"
    depends_on:
      mysqldb: 
        condition: service_healthy
    environment: 
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysqldb:3306/customerdb?allowPublicKeyRetrieval=true&useSSL=false
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=password1
    networks:
      - customer-svc-nw
      
  mysqldb:
    image: mysql:8
    volumes:
      - ./mysql-dump:/docker-entrypoint-initdb.d
    ports: 
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password1
      - MYSQL_DATABASE=personsdb
      - MYSQL_PASSWORD=password1
    healthcheck:
      test: ["CMD", "mysqladmin", "ping","-h", "localhost","-uroot","-ppassword1"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - customer-svc-nw
  adminer:
        image: adminer
        restart: always
        ports: 
            - 8282:8080
  
networks:
  customer-svc-nw:   
   